---
title: "Work Sheet 4c"
author: "Jonathan Cary Sucaldito"
date: "2025-12-11"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(RColorBrewer)   
library(readxl)
```


###1.
```{r}


data(mpg)

write.csv(mpg, "mpg.csv", row.names = FALSE)
```


```{r}
#1A.
mpg <- read.csv("mpg.csv", stringsAsFactors = FALSE)

mpg
```


```{r}
#1B.
str(mpg)

#All characters and factors are categorical
```

```{r}
#1C.
str(mpg)

#All numeric are continous
```
###2.
```{r}
mpg %>%
  group_by(manufacturer) %>%
  summarise(models = n_distinct(model))

```

```{r}
#2A.
unique_models <- mpg %>%
  group_by(manufacturer) %>%
  summarise(unique_models = n_distinct(model)) %>%
  arrange(desc(unique_models))

unique_models
```

```{r}
#2B.

ggplot(unique_models, aes(x = reorder(manufacturer, -unique_models), y = unique_models)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  xlab("Manufacturer") + ylab("Number of Unique Models") +
  ggtitle("Number of Unique Models by Manufacturer") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
#2A.

ggplot(mpg, aes(x = reorder(manufacturer, model, function(x) length(unique(x))), y = model)) +
  geom_point() +
  xlab("Manufacturer") + 
  ylab("Model") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
#2B.

#For me, no. Barplot is more useless and easy to understand.
```

```{r}
#3.

top_20 <- head(mpg, 20)

ggplot(top_20, aes(x = model, y = year)) +
  geom_point() +
  xlab("Model") + ylab("Year") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r}
#4.

mpg %>%
  group_by(model) %>%
  summarise(count = n()) %>%
  arrange(desc(count))
```

```{r}
#4A.

top_20_models <- mpg %>%
  group_by(model) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) %>%
  head(20)

ggplot(top_20_models, aes(x = reorder(model, -count), y = count, fill = model)) +
  geom_bar(stat = "identity") +
  xlab("Model") + ylab("Number of Cars") +
  ggtitle("Top 20 Car Models by Number of Cars") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "none") +
  scale_fill_manual(values = colorRampPalette(brewer.pal(12, "Set3"))(20))     
```

```{r}
#4B.

top_20_models <- mpg %>%
  group_by(model) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) %>%
  head(20)

ggplot(top_20_models, aes(x = model, y = count, fill = model)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  xlab("Number of Cars") + ylab("Model") +
  ggtitle("Top 20 Car Models by Number of Cars") +
  theme(axis.text.y = element_text(size = 9), legend.position = "none")
```

```{r}
#5.

ggplot(mpg, aes(x = cyl, y = displ, color = displ)) +
  geom_point() +
  ggtitle("Relationship between No. of Cylinders and Engine Displacement") +
  xlab("Number of Cylinders") + ylab("Engine Displacement") +
  scale_color_gradient(low = "blue", high = "red")
```
```{r}
#5A.

#Is strong and positive, engines with more cylinders generally have larger displacement.
```

```{r}
#6.

ggplot(mpg, aes(x = displ, y = hwy, color = displ)) +
  geom_point() +
  ggtitle("Relationship between Engine Displacement and Highway MPG") +
  xlab("Engine Displacement (L)") + ylab("Highway MPG") +
  scale_color_gradient(low = "blue", high = "red")
```

```{r}
#6. I AM NOT SURE MAAM IF THE TRAFFIC DATA SET IS CORRECT, I HAVE NO IDEA WHERE TO GET THE DATA

traffic_data <- data.frame(
  Date = as.Date('2025-11-01') + 0:9,
  Location = rep(c("Intersection A", "Intersection B"), each = 5),
  Vehicles = c(120, 150, 130, 160, 140, 200, 210, 190, 205, 220),
  Average_Speed = c(35.5, 34.2, 36.0, 33.8, 34.5, 32.0, 31.5, 33.0, 30.8, 29.5)
)

write.csv(traffic_data, "traffic.csv", row.names = FALSE)

traffic <- read.csv("traffic.csv", stringsAsFactors = FALSE)
```

```{r}
#6A.

str(traffic)
```

```{r}
#6B.

intersection_a <- traffic[traffic$Location == "Intersection A", ]
intersection_b <- traffic[traffic$Location == "Intersection B", ]

print(intersection_a)
print(intersection_b)
```

```{r}
#6C.

ggplot(traffic, aes(x = Date, y = Vehicles, color = Location, group = Location)) +
  geom_line() +
  geom_point() +
  xlab("Date") + ylab("Number of Vehicles") +
  ggtitle("Traffic Over Time by Junction") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r}
#7.

alexa <- read_excel("alexa-file.xlsx")
  
```

```{r}
#7A.

str(alexa)
```

```{r}
#7B.
load("variations.RData")

numeric_col <- names(variations)[sapply(variations, is.numeric)][1]

variations %>%
  group_by(variation) %>%
  summarise(total = sum(.data[[numeric_col]]))

```

```{r}
#7C.
num_col <- names(variations)[sapply(variations, is.numeric)][1]

ggplot(variations, aes(x = variation, y = .data[[num_col]], fill = variation)) +
  geom_bar(stat = "identity") +
  xlab("Variation") + ylab(num_col) +
  ggtitle("Count of Each Variation") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none")
```
```{r}
#7D.
num_col <- names(variations)[sapply(variations, is.numeric)][1]

variations$index <- 1:nrow(variations)

ggplot(variations, aes(x = index, y = .data[[num_col]])) +
  geom_line() +
  geom_point() +
  xlab("Entry Number") +
  ylab("Number of Verified Reviews") +
  ggtitle("Verified Reviews per Entry (No Date Available)") +
  theme_minimal()

#My variations dataset has no date, so I used the entry number as a substitute to create the line plot.
```

```{r}
#7E.
variation_col <- names(variations)[sapply(variations, is.character) | sapply(variations, is.factor)][1]
num_col <- names(variations)[sapply(variations, is.numeric)][1]

variation_summary <- variations %>%
  group_by(.data[[variation_col]]) %>%
  summarise(total = sum(.data[[num_col]], na.rm = TRUE))

variation_summary %>% arrange(desc(total)) %>% head(1)

ggplot(variation_summary,
       aes(x = .data[[variation_col]], y = total, fill = .data[[variation_col]])) +
  geom_col() +
  xlab("Variation") +
  ylab("Total Count") +
  ggtitle("Count per Variation") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none")

#My variations dataset has no ratings, so I used the count values instead to identify which variation has the highest total.
```